[build]
  command = "npm run build"
  publish = "out"    # Ubah ke 'out' karena kita menggunakan output: 'export'

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true