[build]
  command = "npm run build"
  publish = ".next"    # Kembali ke .next

[build.environment]
  NODE_VERSION = "18"
  NEXT_RUNTIME = "nodejs18.x"

[[plugins]]
  package = "@netlify/plugin-nextjs"